trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-20.04

stages:
- stage: CI
  jobs:
  - job:
    steps:
    - task: Bash@3
      displayName: 'Setup Pre-Commit'
      inputs:
        targetType: 'inline'
        script: |
          git config --global url."https://".insteadOf git://
          pip install pre-commit
    - task: Bash@3
      displayName: 'Run pre-commit'
      inputs:
        targetType: 'inline'
        script: 'pre-commit run --all-files'
- stage: dev
  jobs:
  - template: templates/cicd.yaml
    parameters:
        env: dev
- stage: stg
  condition: in(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
  - template: templates/cicd.yaml
    parameters:
        env: stg
- stage: prod
  condition: in(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
  - template: templates/cicd.yaml
    parameters:
        env: prod
